name: BotFather

on:
  workflow_dispatch:

jobs:
  telegram:
    runs-on: ubuntu-latest
    steps:    
    # - name: Step that might fail
    #   run: exit 1
      # continue-on-error: true # Allows subsequent steps to run
    - name: Version Tag
      id: version_tag
      run: |
        echo Version: ${GITHUB_REF_NAME#v}
        echo "VERSION=${GITHUB_REF_NAME#v}" >> "$GITHUB_OUTPUT"

    - name: Step ok
      run: |
        echo ok

    - name: failure message
      if: ${{ failure() }}
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          🔴 Android ${{ steps.version_tag.outputs.VERSION }} build failed ${{ github.ref_name }}

    - name: failure message
      if: ${{ success() }}
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          🟢 Android ${{ steps.version_tag.outputs.VERSION }} release ${{ github.ref_name }}
    
    - name: Step ok2
      run: |
        echo ok2