name: BotFather

on:
  workflow_dispatch:

jobs:
  telegram:
    runs-on: ubuntu-latest
    steps:    
    - name: Version Tag
      id: version_tag
      run: |
        echo Version: ${GITHUB_REF_NAME#v}
        echo "VERSION=${GITHUB_REF_NAME#v}" >> "$GITHUB_OUTPUT"

    - name: Step ok
      run: |
        echo ok

    - name: Step fail 1
      run: exit 1
    - name: Step fail 2
      run: exit 1
      # continue-on-error: true # Allows subsequent steps to run

    - name: Step ok
      run: |
        echo ok

    - name: Get failed jobs
      if: always()
      run: |
        gh api /repos/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID/jobs | jq '.jobs[] | select(.conclusion == "failure") | .name' | echo
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Get failed jobs 2
      if: always()
      run: |
        gh api /repos/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID/jobs --jq '.jobs[] | select(.conclusion == "failure") | .name, .head_branch, (.steps[]|select(.conclusion == "failure")|.name)'
        gh api /repos/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID/jobs --jq '.jobs[] | select(.conclusion == "failure") | .name' | echo
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Tg Build failed
      if: ${{ failure() }}
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          🔴 Android ${{ steps.version_tag.outputs.VERSION }} build failed

    - name: Tg Release
      if: ${{ success() }}
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          🟢 Android ${{ steps.version_tag.outputs.VERSION }} release
    
    - name: Step ok2
      run: |
        echo ok2