name: BotFather

on:
  workflow_dispatch:

jobs:
  telegram:
    runs-on: ubuntu-latest
    steps:
    - name: send message
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          Send message from ${{ github.repository }}.
