name: Sync Forks

on:
  schedule:
    - cron: '0 0 * * 0' #every Sunday
  workflow_dispatch:

permissions:
  contents: write


jobs:
  sync_matrix:
    name: Sync ${{ matrix.repo }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        repo: 
          - Wand-Enhancer
          # - SRE-binwalk
          - SRE-binwalk-ng
          - SRE-jadx
          - SRE-ghidra
          - SRE-CyberChef
          - SRE-john
        include:
          - repo: Wand-Enhancer
            upstream: k1tbyte/Wand-Enhancer
            branch: master
          # - repo: SRE-binwalk
          #   upstream: ReFirmLabs/binwalk
          #   branch: master
          - repo: SRE-binwalk-ng
            upstream: binwalk-ng/binwalk-ng
            branch: main
          - repo: SRE-jadx
            upstream: skylot/jadx
            branch: master
          - repo: SRE-ghidra
            upstream: NationalSecurityAgency/ghidra
            branch: master
          - repo: SRE-CyberChef
            upstream: gchq/CyberChef
            branch: master
          - repo: SRE-john
            upstream: openwall/john
            branch: bleeding-jumbo

    steps:
      - name: Forks Sync
        uses: TobKed/github-forks-sync-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          upstream_repository: ${{ matrix.upstream }}
          target_repository: ZebNoid/${{ matrix.repo }}
          upstream_branch: ${{ matrix.branch }}
          target_branch: ${{ matrix.branch }}
          force: true
          tags: true
